spring.application.name=TAM
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
spring.datasource.username=system
spring.datasource.password=Oracle123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
spring.jpa.hibernate.ddl-auto=none

# Logs
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

#Security
spring.security.oauth2.client.registration.github.client-id=Ov23li9Bka8Uwk6pKEMT
spring.security.oauth2.client.registration.github.client-secret=7620e3b040ff39dec2d7177503077ba4a168572a
spring.security.oauth2.client.registration.github.scope=read:user
spring.security.oauth2.clinet.resistration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

#Custom Login_Auth with only GitHub 
spring.security.oauth2.client.registration.github.client-name=GitHub



#No_Endpoint_Exception
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false