CREATE TABLE STOCKTRADES (  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    symbol VARCHAR2(20),
    trade_date DATE,
    quantity NUMBER,
    price NUMBER,
    type VARCHAR2(10), -- BUY or SELL
    profit_loss NUMBER,
    country VARCHAR2(50),
    industry_tag VARCHAR2(100)
);