import oracledb
import pandas as pd
import os


username = os.getenv('DB_USER', 'system')
password = os.getenv('DB_PASSWORD', 'Oracle123')
dsn = f"{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '1521')}/{os.getenv('DB_SERVICE', 'XEPDB1')}"

connection = oracledb.connect(user=username, password=password, dsn=dsn)
cursor = connection.cursor()


cursor.execute("""
    BEGIN
        EXECUTE IMMEDIATE '
            CREATE TABLE STOCKTRADES (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                symbol VARCHAR2(10),
                trade_date DATE,
                quantity NUMBER,
                price NUMBER(10, 2),
                type VARCHAR2(10),
                profit_loss NUMBER(10,2),
                country VARCHAR2(50),
                industry_tag VARCHAR2(100)
            )
        ';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
""")
connection.commit()
print("Checked and created STOCKTRADES table (if not exists)")
