import os
import pandas as pd
import oracledb  # no need to call init_oracle_client

# === Step 1: Load the cleaned CSV ===
csv_file = "data/cleaned_trades.csv"
df = pd.read_csv(csv_file)

# === Step 2: Connection details
username = "System"
password = "Oracle123"
host = os.getenv("DB_HOST", "localhost")
port = os.getenv("DB_PORT", "1521")
service_name = os.getenv("DB_SERVICE", "XEPDB1")

dsn = f"{host}:{port}/{service_name}"

# === Step 3: Connect to Oracle using THIN mode (default)
connection = oracledb.connect(user=username, password=password, dsn=dsn)
cursor = connection.cursor()

custor.execute("""
				SELECT COUNT(*)
				FROM all_tables
				WHERE table_name = 'STOCKTRADES'
				""")
table_exists = cursor.fetchone()[0]

if table_exists == 0:
	print("STOCKTRADES table does not exist")
	cursor.execute(""" 
			 CREATE TABLE STOCKTRADES (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            symbol VARCHAR2(10),
            trade_date DATE,
            quantity NUMBER,
            price NUMBER(10, 2),
            type VARCHAR2(10),
            profit_loss NUMBER(10,2),
            country VARCHAR2(50),
            industry_tag VARCHAR2(100)
        )
    """)
    connection.commit()
    print("Table STOCKTRADES creates")
else:
	print(" STOCKTRADES Table already exists")

# === Step 4: Insert SQL
insert_sql = """
    INSERT INTO STOCKTRADES (
        trade_date, symbol, quantity, price, type, profit_loss, country, industry_tag
    ) VALUES (
        TO_DATE(:1, 'YYYY-MM-DD'),
        :2, :3, :4, :5, :6, :7, :8
    )
"""

# === Step 5: Insert rows
for _, row in df.iterrows():
    cursor.execute(insert_sql, (
        row['trade_date'],
        row['symbol'],
        int(row['quantity']),
        float(row['price']),
        row['type'],
        float(row['profit_loss']),
        row['country'],
        row['industry_tag']
    ))

# === Step 6: Done
connection.commit()
cursor.close()
connection.close()

print(" Data successfully inserted into the 'trades' table!")
