name: Build and Test Spring Boot Microservice

on:
  push:
    branches:
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      oracle-db:
        image: gvenzl/oracle-xe
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: Oracle123
        options: >-
          --health-cmd "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/Oracle123@localhost/XEPDB1 || exit 1"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 15
          --shm-size 1g

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python and install libraries
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip libaio-dev
          pip3 install oracledb pandas

      - name: Wait for Oracle DB to fully start
        run: sleep 240

      - name: Load Test Data into Oracle
        run: |
          echo "Running load_trades.py to create table and insert data..."
          python3 data/load_trades.py

      - name: Build and Test Spring Boot Application
        run: |
          ./mvnw clean install -Dspring.profiles.active=ci
