name: Build and Test Spring Boot Microservice

on:
  push:
    branches:
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      oracle-db:
        image: gvenzl/oracle-xe
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: Oracle123
          ORACLE_DATABASE: XEPDB1
        options: >-
          --health-cmd "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/Oracle123@localhost/XEPDB1 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --mount type=bind,source=${{ github.workspace }}/data,target=/data

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python and Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install oracledb pandas

      - name: Wait for Oracle DB to fully start
        run: sleep 180

      - name: Create Application Schema inside Oracle DB
        run: |
          echo "Creating STOCKTRADES table inside Oracle DB..."
          docker exec oracle-db bash -c "cat /data/DB_CreateTable.sql | sqlplus system/Oracle123@localhost/XEPDB1"

      - name: Load Test Data into Oracle
        run: |
          echo "Loading cleaned trades CSV into Oracle DB..."
          python3 data/load_trades.py

      - name: Build and Test Spring Boot Application
        run: |
          ./mvnw clean install -Dspring.profiles.active=ci
